#!/usr/bin/env python3
"""Write provenance/DATA_INVENTORY.md: where each processed dataset lives.

Answers "where are the processed features for figure X" from the tree itself rather
than from memory, so it stays true as things move.

    python scripts/data_inventory.py
"""
from __future__ import annotations

import os
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
OUT = REPO / "provenance" / "DATA_INVENTORY.md"

# (dataset, panels, experiment key, glob patterns relative to the repo root)
GROUPS = [
    ("3D spheroid Cell Painting", "Fig 2–4, 5d–f, 6e", "exp1_main",
     ["data/exp1_main/grit_data_MIP_*.parquet",
      "data/exp1_main/grit_data_aggregates_*.parquet",
      "data/exp1_main/selected_data_MIP_*.parquet",
      "data/exp1_main/selected_data_aggregates_*.parquet",
      "data/exp1_main/slices/*"]),
    ("2D monolayer Cell Painting (4-plate run)", "Fig 5a–d, Suppl 5", "exp1_main",
     ["data/exp1_main/grit_data_2D_*.parquet",
      "data/exp1_main/selected_data_2D_*.parquet"]),
    ("Per-slice profiles for the Fig 2g PCA", "Fig 2g", "exp1_main",
     ["data/exp1_main/normalized_data_merged_HCT116.csv"]),
    ("Robustness — spheroid size / seeding", "Suppl 3c", "exp2_spheroid_size",
     ["data/exp2_spheroid_size/*.parquet"]),
    ("Robustness — clearing, magnification, z-density", "Suppl 3b/d/e", "exp3_clearing_mag_z",
     ["data/exp3_clearing_mag_z/*.parquet"]),
    ("Objective comparison (air vs water immersion)", "Suppl 4h–i", "exp4_objective",
     ["data/exp4_objective/*.parquet"]),
    ("EdU / γH2AX imaging", "Fig 6a–b", "—",
     ["analysis/3_Figure6/EdU/data/*.csv"]),
    ("Bulk RNA-seq", "Fig 6c–d, Suppl 6", "—",
     ["analysis/3_Figure6/DEG/data/*.csv"]),
    ("Expert-annotation segmentation", "Suppl 2d–e", "—",
     ["analysis/3_SupplFigure2/data/*.csv",
      "analysis/3_SupplFigure2/data/spher-colo52/*/segmentation_output/*.csv"]),
    ("Suppl 3g/3h cached aggregations", "Suppl 3g–h", "—",
     ["analysis/3_SupplFigure3/data/*.csv"]),
    ("Suppl 5e similarity matrices", "Suppl 5e", "—",
     ["analysis/3_SupplFigure5/data/*.csv"]),
]

HEADER = """# Processed data inventory

Where each processed dataset behind the figures lives, and how much of it there is.
Generated by `scripts/data_inventory.py`; re-run it after moving anything.

Rows marked **linked** are symlinks into the working tree this release was ported from
(`colopaint3D/`), created by `scripts/download_data.py --from-local --link`. They are the
same bytes, not copies — a deposition needs the resolved files, not the links.
"""

FOOTER = """
## Not included here

The per-slice CellProfiler feature dumps (`FeaturesImages_*`, ~19.5 GB) live under
`data/features/` and feed `1_Data`/`2_Processing`, not the figures — the figures run from
the tables above. Raw images are to be deposited separately in the BioImage Archive, and
the CellProfiler `.cppipe` pipelines and Cellpose models are in no repo at all
(see `provenance/KNOWN_ISSUES.md`).
"""


def human(n: float) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024:
            return f"{n:.0f} {unit}"
        n /= 1024
    return f"{n:.1f} TB"


def _location(dirs: set[str], linked: int, total: int) -> str:
    if linked == total and total:
        return "linked → `colopaint3D/`"
    common = os.path.commonpath(list(dirs)) if dirs else ""
    label = f"`{common}/`" if common else "—"
    return f"{label} + linked" if linked else label


def main() -> int:
    rows, grand = [], 0
    for title, panels, exp, patterns in GROUPS:
        dirs: set[str] = set()
        count = linked = 0
        size = 0
        for pat in patterns:
            for p in sorted(REPO.glob(pat)):
                if p.is_dir():
                    continue
                real = p.resolve()
                if not real.exists():
                    continue
                count += 1
                size += real.stat().st_size
                if p.is_symlink():
                    linked += 1
                else:
                    dirs.add(str(p.parent.relative_to(REPO)))
        grand += size
        rows.append(f"| {title} | {panels} | `{exp}` | {count} | {human(size)} | "
                    f"{_location(dirs, linked, count)} |")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        HEADER
        + "\n| Dataset | Panels | Experiment | Files | Size | Location |\n|---|---|---|---|---|---|\n"
        + "\n".join(rows)
        + f"\n\n**Total processed data behind the figures: {human(grand)}**\n"
        + FOOTER
    )
    print(f"wrote {OUT.relative_to(REPO)}  —  {len(rows)} datasets, {human(grand)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
